version: '3.4'

services:
  sampleproject:
    image: sampleproject
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    volumes:
      - /var/dockerfiles/react-frontend:/app
